name: Run GitHub Backup

on:
    push:
        branches: ["main"]
    schedule:
        - cron: "0 0 1,15 * *"

env:
    BASE_DIR: ${{ vars.BASE_DIR }}
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}

jobs:
    build:
        runs-on: self-hosted
        timeout-minutes: 3600
        if: contains(github.event.head_commit.message, 'skip ci') == false
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: Install Dependencies
              run: npm install

            - name: Run GitHub Backup
              run: npm run backup
